### ISSUE TITLE
XCode 9 compile failed

### ISSUE THREAD

**Issue by crossle** [1024jp/GzipSwift#14]
GzipSwift/zlib/module.modulemap:1:8: note: previously defined here
module zlib [system] {
       ^
<unknown>:0: error: could not build Objective-C module 'Gzip'

**Comment by ramki982** [comment]
+1 - facing the same issue

**Comment by crossle** [comment]
remove zib work well

**Comment by ramki982** [comment]
yes removing it from module map seems to fix it

**Comment by HarukaMa** [comment]
It seems that 10.13 SDK has already included `zlib` in objc module map, so we won't need to manually include that module anymore.

**Comment by crossle** [comment]
@HarukaMa  YES

**Comment by 1024jp** [comment]
I've just pushed [swift4](https://github.com/1024jp/GzipSwift/tree/swift4) branch. Give it a try.

I'll keep it as a branch until the stable Xcode 9 is released.

**Comment by richardPFisk** [comment]
Unfortunately, I'm still getting the same problem in XCode9-beta4:

```
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/module.modulemap:1871:8: error: redefinition of module 'zlib'
module zlib [system] [extern_c] {
       ^
/Users/blah/Pods/GzipSwift/zlib/module.modulemap:1:8: note: previously defined here
module zlib [system] {
       ^
<unknown>:0: error: could not build Objective-C module 'Gzip'
```

**Comment by lukegardiner** [comment]
Thanks. Solved my problems building the app with Xcode9 GM

**Comment by BrendanBuono** [comment]
Can we get the swift4 branch merged soon with the Release of XCode 9 GM?

**Comment by 1024jp** [comment]
@BrendanBuono Well, I'll do it in this weekend.

**Comment by 1024jp** [comment]
I've just merged the swift4 branch to master branch (develop as well).

**Comment by BrendanBuono** [comment]
Thanks! Could we get the Cocoapod updated as well please?

**Comment by ravijain412** [comment]
I tried Gzip beta and it worked on Xcode 9 but it started failing on Xcode 8. We are using GzipSwift as a dependency in our sdk. If we ship it with Xcode 9 , it will break for developers who are using Xcode 8. Any solution to this problem ?

**Comment by 1024jp** [comment]
@BrendanBuono 
Oups, I totally forgot about that. I'll update it when I have a time (Sorry, I'm bussy recently...).

@ravijain412 
Use GzipSwift 3.1.4 for Xcode 8/Swift 3.x.

**Comment by crossle** [comment]
How to use swift3.x version on Xcode 9?

**Comment by BrendanBuono** [comment]
No problem, @1024jp thank you!

**Comment by amayatsky** [comment]
pod 'GzipSwift', :git => 'https://github.com/1024jp/GzipSwift.git', :branch => 'master' works for a time being

**Comment by crossle** [comment]
Already switch to Swift4, work well

**Comment by 1024jp** [comment]
Now, I've pushed GzipSwift 4.0 to CocoaPods server :)
Give it try.

**Comment by 1024jp** [comment]
Note: I'll remove swift4 branch at some time point in October.

**Comment by maningyt** [comment]
@1024jp Just tried pod install, still "Installing GzipSwift(3.1.4)"

**Comment by amayatsky** [comment]
Try running pod repo update first?

**Comment by maningyt** [comment]
@amayatsky  resolved by changing podfile: pod 'GzipSwift', '~> 4.0.0’
Doesn't work without version. 
Tried: pod update GzipSwift  first, did updated to 4.0.0, but caused compile error because of podfile.lock. So I deleted the pod folder, and ran the new podfile. Can build now.

**Comment by sonamsamdupkhangsar** [comment]
Hi
I am using GzipSwift api on Xcode 8 (Swift3) .  I can build and deploy to Simulator fine but when targeting a Ipad device I get errors like the following:

> let unzipped = try! data.gunzipped()

I see this error on build for iPad device:
> Value of type 'Data' has no member 'gunzipped'

**Comment by 1024jp** [comment]
I'll remove swift4 branch since the branch was merged to the master branch as well as develop.
